export const ROUTES = {
  home: "/",
  productDetail: "/products/:productId",
  shop: "/shop",
  search: "/search",
  compare: "/compare",
  about: "/about",
  contact: "/contact",
  policies: {
    terms: "/policies/terms",
    privacy: "/policies/privacy",
    returnPolicy: "/policies/return",
  },
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    verifyEmail: "/auth/verify-email",
    forgotPassword: "/auth/forgot-password",
  },
  customer: {
    profile: "/profile",
    notifications: "/notifications",
    cart: "/cart",
    checkout: "/checkout",
    orders: "/orders",
    orderDetail: "/orders/:id",
    warranty: "/warranty",
    newWarranty: "/warranty/new",
  },
  staff: {
    dashboard: "/staff",
    orders: "/staff/orders",
    orderDetail: "/staff/orders/:id",
    warranties: "/staff/warranties",
    warrantyDetail: "/staff/warranties/:id",
    products: "/staff/products",
    productDetail: "/staff/products/:id",
    customers: "/staff/customers",
    customerDetail: "/staff/customers/:id",
    support: "/staff/support",
  },
  owner: {
    dashboard: "/owner",
    products: "/owner/products",
    productCreate: "/owner/products/new",
    productDetail: "/owner/products/:id",
    inventory: "/owner/inventory",
    suppliers: "/owner/suppliers",
    importReceipts: "/owner/import-receipts",
    customers: "/owner/customers",
    customerDetail: "/owner/customers/:id",
    warranties: "/owner/warranties",
    warrantyDetail: "/owner/warranties/:id",
    staff: "/owner/staff",
    staffDetail: "/owner/staff/:id",
    vouchers: "/owner/vouchers",
    reports: "/owner/reports",
    content: "/owner/content",
  },
  errors: {
    forbidden: "/forbidden",
    notFound: "*",
  },
} as const;
